package com.importproject.dao;

import com.importproject.enetity.Assertion;

public interface AssertionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assertion
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int deleteByPrimaryKey(Integer assetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assertion
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insert(Assertion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assertion
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insertSelective(Assertion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assertion
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    Assertion selectByPrimaryKey(Integer assetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assertion
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKeySelective(Assertion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assertion
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKey(Assertion record);
}