package com.importproject.dao;

import com.importproject.enetity.Method;

public interface MethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int deleteByPrimaryKey(Integer methodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insert(Method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insertSelective(Method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    Method selectByPrimaryKey(Integer methodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKeySelective(Method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKey(Method record);
}