package com.importproject.dao;

import com.importproject.enetity.Mock;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface MockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int deleteByPrimaryKey(Integer mockid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insert(Mock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insertSelective(Mock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    Mock selectByPrimaryKey(Integer mockid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKeySelective(Mock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKey(Mock record);
}