package com.importproject.dao;

import com.importproject.enetity.ModeMethod;

public interface ModeMethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_method_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int deleteByPrimaryKey(Integer mMethodidM);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_method_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insert(ModeMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_method_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insertSelective(ModeMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_method_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    ModeMethod selectByPrimaryKey(Integer mMethodidM);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_method_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKeySelective(ModeMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_method_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKey(ModeMethod record);
}