package com.importproject.dao;

import com.importproject.enetity.Project;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int deleteByPrimaryKey(Integer projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    Project selectByPrimaryKey(Integer projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKey(Project record);

    List<Project> selectAll();
}