package com.importproject.enetity;

import java.io.Serializable;

public class Example implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example_t.example_id
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer exampleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example_t.mockid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer mockid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example_t.e_frameid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer eFrameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example_t.exampledesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String exampledesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example_t.examplevalue
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String examplevalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table example_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example_t.example_id
     *
     * @return the value of example_t.example_id
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getExampleId() {
        return exampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example_t.example_id
     *
     * @param exampleId the value for example_t.example_id
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setExampleId(Integer exampleId) {
        this.exampleId = exampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example_t.mockid
     *
     * @return the value of example_t.mockid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getMockid() {
        return mockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example_t.mockid
     *
     * @param mockid the value for example_t.mockid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setMockid(Integer mockid) {
        this.mockid = mockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example_t.e_frameid
     *
     * @return the value of example_t.e_frameid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer geteFrameid() {
        return eFrameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example_t.e_frameid
     *
     * @param eFrameid the value for example_t.e_frameid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void seteFrameid(Integer eFrameid) {
        this.eFrameid = eFrameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example_t.exampledesc
     *
     * @return the value of example_t.exampledesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getExampledesc() {
        return exampledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example_t.exampledesc
     *
     * @param exampledesc the value for example_t.exampledesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setExampledesc(String exampledesc) {
        this.exampledesc = exampledesc == null ? null : exampledesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example_t.examplevalue
     *
     * @return the value of example_t.examplevalue
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getExamplevalue() {
        return examplevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example_t.examplevalue
     *
     * @param examplevalue the value for example_t.examplevalue
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setExamplevalue(String examplevalue) {
        this.examplevalue = examplevalue == null ? null : examplevalue.trim();
    }
}