package com.importproject.enetity;

import java.io.Serializable;

public class ModeAbstract implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_abstract_t.abstractid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer abstractid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_abstract_t.implid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer implid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_abstract_t.abstractdesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String abstractdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_abstract_t.abstractname
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String abstractname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_abstract_t.at_methodid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer atMethodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_abstract_t.a_frameid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer aFrameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table model_abstract_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_abstract_t.abstractid
     *
     * @return the value of model_abstract_t.abstractid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getAbstractid() {
        return abstractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_abstract_t.abstractid
     *
     * @param abstractid the value for model_abstract_t.abstractid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setAbstractid(Integer abstractid) {
        this.abstractid = abstractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_abstract_t.implid
     *
     * @return the value of model_abstract_t.implid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getImplid() {
        return implid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_abstract_t.implid
     *
     * @param implid the value for model_abstract_t.implid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setImplid(Integer implid) {
        this.implid = implid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_abstract_t.abstractdesc
     *
     * @return the value of model_abstract_t.abstractdesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getAbstractdesc() {
        return abstractdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_abstract_t.abstractdesc
     *
     * @param abstractdesc the value for model_abstract_t.abstractdesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setAbstractdesc(String abstractdesc) {
        this.abstractdesc = abstractdesc == null ? null : abstractdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_abstract_t.abstractname
     *
     * @return the value of model_abstract_t.abstractname
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getAbstractname() {
        return abstractname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_abstract_t.abstractname
     *
     * @param abstractname the value for model_abstract_t.abstractname
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setAbstractname(String abstractname) {
        this.abstractname = abstractname == null ? null : abstractname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_abstract_t.at_methodid
     *
     * @return the value of model_abstract_t.at_methodid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getAtMethodid() {
        return atMethodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_abstract_t.at_methodid
     *
     * @param atMethodid the value for model_abstract_t.at_methodid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setAtMethodid(Integer atMethodid) {
        this.atMethodid = atMethodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_abstract_t.a_frameid
     *
     * @return the value of model_abstract_t.a_frameid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getaFrameid() {
        return aFrameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_abstract_t.a_frameid
     *
     * @param aFrameid the value for model_abstract_t.a_frameid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setaFrameid(Integer aFrameid) {
        this.aFrameid = aFrameid;
    }
}