package com.mybatsigenerator.dao;

import com.importproject.enetity.Example;

public interface ExampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int deleteByPrimaryKey(Integer exampleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insert(Example record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insertSelective(Example record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    Example selectByPrimaryKey(Integer exampleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKeySelective(Example record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKey(Example record);
}