package com.mybatsigenerator.dao;

import com.mybatsigenerator.model.Mock;

public interface MockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int deleteByPrimaryKey(Integer mockid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int insert(Mock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int insertSelective(Mock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    Mock selectByPrimaryKey(Integer mockid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int updateByPrimaryKeySelective(Mock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int updateByPrimaryKey(Mock record);
}