package com.mybatsigenerator.dao;

import com.mybatsigenerator.model.ModeParam;

public interface ModeParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_param_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int deleteByPrimaryKey(Integer paramid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_param_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int insert(ModeParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_param_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int insertSelective(ModeParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_param_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    ModeParam selectByPrimaryKey(Integer paramid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_param_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int updateByPrimaryKeySelective(ModeParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_param_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int updateByPrimaryKey(ModeParam record);
}