package com.mybatsigenerator.dao;

import com.importproject.enetity.ModeAbstract;

public interface ModeAbstractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_abstract_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int deleteByPrimaryKey(Integer abstractid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_abstract_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insert(ModeAbstract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_abstract_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insertSelective(ModeAbstract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_abstract_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    ModeAbstract selectByPrimaryKey(Integer abstractid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_abstract_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKeySelective(ModeAbstract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_abstract_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKey(ModeAbstract record);
}