package com.mybatsigenerator.dao;

import com.mybatsigenerator.model.Project;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int deleteByPrimaryKey(Integer projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    Project selectByPrimaryKey(Integer projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    int updateByPrimaryKey(Project record);
}