package com.importproject.dao;

import com.importproject.enetity.Interface;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface InterfaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int deleteByPrimaryKey(String interfaceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insert(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int insertSelective(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    Interface selectByPrimaryKey(String interfaceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKeySelective(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    int updateByPrimaryKey(Interface record);
}