package com.mybatsigenerator.model;

import java.io.Serializable;

public class Assertion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assertion.assetid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer assetid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assertion.m_methodid_m
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer mMethodidM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assertion.assetname
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private String assetname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assertion.assetdesc
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private String assetdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assertion.assetvalue
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private String assetvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assertion.at_methodid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer atMethodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assertion.asset_frameid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer assetFrameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table assertion
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assertion.assetid
     *
     * @return the value of assertion.assetid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getAssetid() {
        return assetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assertion.assetid
     *
     * @param assetid the value for assertion.assetid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setAssetid(Integer assetid) {
        this.assetid = assetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assertion.m_methodid_m
     *
     * @return the value of assertion.m_methodid_m
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getmMethodidM() {
        return mMethodidM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assertion.m_methodid_m
     *
     * @param mMethodidM the value for assertion.m_methodid_m
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setmMethodidM(Integer mMethodidM) {
        this.mMethodidM = mMethodidM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assertion.assetname
     *
     * @return the value of assertion.assetname
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public String getAssetname() {
        return assetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assertion.assetname
     *
     * @param assetname the value for assertion.assetname
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setAssetname(String assetname) {
        this.assetname = assetname == null ? null : assetname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assertion.assetdesc
     *
     * @return the value of assertion.assetdesc
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public String getAssetdesc() {
        return assetdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assertion.assetdesc
     *
     * @param assetdesc the value for assertion.assetdesc
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setAssetdesc(String assetdesc) {
        this.assetdesc = assetdesc == null ? null : assetdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assertion.assetvalue
     *
     * @return the value of assertion.assetvalue
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public String getAssetvalue() {
        return assetvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assertion.assetvalue
     *
     * @param assetvalue the value for assertion.assetvalue
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setAssetvalue(String assetvalue) {
        this.assetvalue = assetvalue == null ? null : assetvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assertion.at_methodid
     *
     * @return the value of assertion.at_methodid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getAtMethodid() {
        return atMethodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assertion.at_methodid
     *
     * @param atMethodid the value for assertion.at_methodid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setAtMethodid(Integer atMethodid) {
        this.atMethodid = atMethodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assertion.asset_frameid
     *
     * @return the value of assertion.asset_frameid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getAssetFrameid() {
        return assetFrameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assertion.asset_frameid
     *
     * @param assetFrameid the value for assertion.asset_frameid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setAssetFrameid(Integer assetFrameid) {
        this.assetFrameid = assetFrameid;
    }
}