package com.importproject.enetity;

import java.io.Serializable;

public class Method implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_t.methodid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer methodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_t.fileid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer fileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_t.projectid_m
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String projectidM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_t.methodname
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String methodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_t.methoddesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String methoddesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table method_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_t.methodid
     *
     * @return the value of method_t.methodid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getMethodid() {
        return methodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_t.methodid
     *
     * @param methodid the value for method_t.methodid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setMethodid(Integer methodid) {
        this.methodid = methodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_t.fileid
     *
     * @return the value of method_t.fileid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_t.fileid
     *
     * @param fileid the value for method_t.fileid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_t.projectid_m
     *
     * @return the value of method_t.projectid_m
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getProjectidM() {
        return projectidM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_t.projectid_m
     *
     * @param projectidM the value for method_t.projectid_m
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setProjectidM(String projectidM) {
        this.projectidM = projectidM == null ? null : projectidM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_t.methodname
     *
     * @return the value of method_t.methodname
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getMethodname() {
        return methodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_t.methodname
     *
     * @param methodname the value for method_t.methodname
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setMethodname(String methodname) {
        this.methodname = methodname == null ? null : methodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_t.methoddesc
     *
     * @return the value of method_t.methoddesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getMethoddesc() {
        return methoddesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_t.methoddesc
     *
     * @param methoddesc the value for method_t.methoddesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setMethoddesc(String methoddesc) {
        this.methoddesc = methoddesc == null ? null : methoddesc.trim();
    }
}