package com.mybatsigenerator.model;

import java.io.Serializable;

public class ModeMethod implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_method_t.m_methodid_m
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer mMethodidM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_method_t.interfaceid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private String interfaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_method_t.abstractid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer abstractid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_method_t.implid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer implid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_method_t.m_methodname
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private String mMethodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_method_t.m_methoddesc
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private String mMethoddesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_method_t.m_paramid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer mParamid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_method_t.m_returntype
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private String mReturntype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_method_t.m_describetype
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private String mDescribetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_method_t.m_mockid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer mMockid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_method_t.m_frameid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer mFrameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table model_method_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_method_t.m_methodid_m
     *
     * @return the value of model_method_t.m_methodid_m
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getmMethodidM() {
        return mMethodidM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_method_t.m_methodid_m
     *
     * @param mMethodidM the value for model_method_t.m_methodid_m
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setmMethodidM(Integer mMethodidM) {
        this.mMethodidM = mMethodidM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_method_t.interfaceid
     *
     * @return the value of model_method_t.interfaceid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public String getInterfaceid() {
        return interfaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_method_t.interfaceid
     *
     * @param interfaceid the value for model_method_t.interfaceid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setInterfaceid(String interfaceid) {
        this.interfaceid = interfaceid == null ? null : interfaceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_method_t.abstractid
     *
     * @return the value of model_method_t.abstractid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getAbstractid() {
        return abstractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_method_t.abstractid
     *
     * @param abstractid the value for model_method_t.abstractid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setAbstractid(Integer abstractid) {
        this.abstractid = abstractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_method_t.implid
     *
     * @return the value of model_method_t.implid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getImplid() {
        return implid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_method_t.implid
     *
     * @param implid the value for model_method_t.implid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setImplid(Integer implid) {
        this.implid = implid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_method_t.m_methodname
     *
     * @return the value of model_method_t.m_methodname
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public String getmMethodname() {
        return mMethodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_method_t.m_methodname
     *
     * @param mMethodname the value for model_method_t.m_methodname
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setmMethodname(String mMethodname) {
        this.mMethodname = mMethodname == null ? null : mMethodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_method_t.m_methoddesc
     *
     * @return the value of model_method_t.m_methoddesc
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public String getmMethoddesc() {
        return mMethoddesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_method_t.m_methoddesc
     *
     * @param mMethoddesc the value for model_method_t.m_methoddesc
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setmMethoddesc(String mMethoddesc) {
        this.mMethoddesc = mMethoddesc == null ? null : mMethoddesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_method_t.m_paramid
     *
     * @return the value of model_method_t.m_paramid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getmParamid() {
        return mParamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_method_t.m_paramid
     *
     * @param mParamid the value for model_method_t.m_paramid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setmParamid(Integer mParamid) {
        this.mParamid = mParamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_method_t.m_returntype
     *
     * @return the value of model_method_t.m_returntype
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public String getmReturntype() {
        return mReturntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_method_t.m_returntype
     *
     * @param mReturntype the value for model_method_t.m_returntype
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setmReturntype(String mReturntype) {
        this.mReturntype = mReturntype == null ? null : mReturntype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_method_t.m_describetype
     *
     * @return the value of model_method_t.m_describetype
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public String getmDescribetype() {
        return mDescribetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_method_t.m_describetype
     *
     * @param mDescribetype the value for model_method_t.m_describetype
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setmDescribetype(String mDescribetype) {
        this.mDescribetype = mDescribetype == null ? null : mDescribetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_method_t.m_mockid
     *
     * @return the value of model_method_t.m_mockid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getmMockid() {
        return mMockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_method_t.m_mockid
     *
     * @param mMockid the value for model_method_t.m_mockid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setmMockid(Integer mMockid) {
        this.mMockid = mMockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_method_t.m_frameid
     *
     * @return the value of model_method_t.m_frameid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getmFrameid() {
        return mFrameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_method_t.m_frameid
     *
     * @param mFrameid the value for model_method_t.m_frameid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setmFrameid(Integer mFrameid) {
        this.mFrameid = mFrameid;
    }
}