package com.mybatsigenerator.model;

import java.io.Serializable;

public class ModeImpl implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mode_impl_t.implid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer implid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mode_impl_t.implname
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private String implname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mode_impl_t.impldesc
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private String impldesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mode_impl_t.i_abstractid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer iAbstractid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mode_impl_t.i_interfaceid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer iInterfaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mode_impl_t.i_methodid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer iMethodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mode_impl_t.i_frameid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private Integer iFrameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mode_impl_t
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mode_impl_t.implid
     *
     * @return the value of mode_impl_t.implid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getImplid() {
        return implid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mode_impl_t.implid
     *
     * @param implid the value for mode_impl_t.implid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setImplid(Integer implid) {
        this.implid = implid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mode_impl_t.implname
     *
     * @return the value of mode_impl_t.implname
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public String getImplname() {
        return implname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mode_impl_t.implname
     *
     * @param implname the value for mode_impl_t.implname
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setImplname(String implname) {
        this.implname = implname == null ? null : implname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mode_impl_t.impldesc
     *
     * @return the value of mode_impl_t.impldesc
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public String getImpldesc() {
        return impldesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mode_impl_t.impldesc
     *
     * @param impldesc the value for mode_impl_t.impldesc
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setImpldesc(String impldesc) {
        this.impldesc = impldesc == null ? null : impldesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mode_impl_t.i_abstractid
     *
     * @return the value of mode_impl_t.i_abstractid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getiAbstractid() {
        return iAbstractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mode_impl_t.i_abstractid
     *
     * @param iAbstractid the value for mode_impl_t.i_abstractid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setiAbstractid(Integer iAbstractid) {
        this.iAbstractid = iAbstractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mode_impl_t.i_interfaceid
     *
     * @return the value of mode_impl_t.i_interfaceid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getiInterfaceid() {
        return iInterfaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mode_impl_t.i_interfaceid
     *
     * @param iInterfaceid the value for mode_impl_t.i_interfaceid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setiInterfaceid(Integer iInterfaceid) {
        this.iInterfaceid = iInterfaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mode_impl_t.i_methodid
     *
     * @return the value of mode_impl_t.i_methodid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getiMethodid() {
        return iMethodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mode_impl_t.i_methodid
     *
     * @param iMethodid the value for mode_impl_t.i_methodid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setiMethodid(Integer iMethodid) {
        this.iMethodid = iMethodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mode_impl_t.i_frameid
     *
     * @return the value of mode_impl_t.i_frameid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public Integer getiFrameid() {
        return iFrameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mode_impl_t.i_frameid
     *
     * @param iFrameid the value for mode_impl_t.i_frameid
     *
     * @mbggenerated Sun Jan 17 10:55:21 CST 2021
     */
    public void setiFrameid(Integer iFrameid) {
        this.iFrameid = iFrameid;
    }
}