package com.importproject.enetity;

import java.io.Serializable;

public class File implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_t.fileid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer fileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_t.directoryid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer directoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_t.projectid_f
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String projectidF;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_t.filename
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_t.filedesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String filedesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_t.method_id_fk
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer methodIdFk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_t.projectroot_f
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String projectrootF;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_t.filetype
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String filetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_t.fileid
     *
     * @return the value of file_t.fileid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_t.fileid
     *
     * @param fileid the value for file_t.fileid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_t.directoryid
     *
     * @return the value of file_t.directoryid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getDirectoryid() {
        return directoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_t.directoryid
     *
     * @param directoryid the value for file_t.directoryid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setDirectoryid(Integer directoryid) {
        this.directoryid = directoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_t.projectid_f
     *
     * @return the value of file_t.projectid_f
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getProjectidF() {
        return projectidF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_t.projectid_f
     *
     * @param projectidF the value for file_t.projectid_f
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setProjectidF(String projectidF) {
        this.projectidF = projectidF == null ? null : projectidF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_t.filename
     *
     * @return the value of file_t.filename
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_t.filename
     *
     * @param filename the value for file_t.filename
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_t.filedesc
     *
     * @return the value of file_t.filedesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getFiledesc() {
        return filedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_t.filedesc
     *
     * @param filedesc the value for file_t.filedesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setFiledesc(String filedesc) {
        this.filedesc = filedesc == null ? null : filedesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_t.method_id_fk
     *
     * @return the value of file_t.method_id_fk
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getMethodIdFk() {
        return methodIdFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_t.method_id_fk
     *
     * @param methodIdFk the value for file_t.method_id_fk
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setMethodIdFk(Integer methodIdFk) {
        this.methodIdFk = methodIdFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_t.projectroot_f
     *
     * @return the value of file_t.projectroot_f
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getProjectrootF() {
        return projectrootF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_t.projectroot_f
     *
     * @param projectrootF the value for file_t.projectroot_f
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setProjectrootF(String projectrootF) {
        this.projectrootF = projectrootF == null ? null : projectrootF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_t.filetype
     *
     * @return the value of file_t.filetype
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_t.filetype
     *
     * @param filetype the value for file_t.filetype
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setFiletype(String filetype) {
        this.filetype = filetype == null ? null : filetype.trim();
    }
}