package com.importproject.enetity;

import java.io.Serializable;

public class Mock implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_t.mockid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer mockid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_t.m_methodid_m
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer mMethodidM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_t.mockname
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String mockname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_t.mockvalue
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String mockvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_t.mockdesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String mockdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_t.m_exampleid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer mExampleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_t.mock_frameid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer mockFrameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mock_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_t.mockid
     *
     * @return the value of mock_t.mockid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getMockid() {
        return mockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_t.mockid
     *
     * @param mockid the value for mock_t.mockid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setMockid(Integer mockid) {
        this.mockid = mockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_t.m_methodid_m
     *
     * @return the value of mock_t.m_methodid_m
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getmMethodidM() {
        return mMethodidM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_t.m_methodid_m
     *
     * @param mMethodidM the value for mock_t.m_methodid_m
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setmMethodidM(Integer mMethodidM) {
        this.mMethodidM = mMethodidM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_t.mockname
     *
     * @return the value of mock_t.mockname
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getMockname() {
        return mockname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_t.mockname
     *
     * @param mockname the value for mock_t.mockname
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setMockname(String mockname) {
        this.mockname = mockname == null ? null : mockname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_t.mockvalue
     *
     * @return the value of mock_t.mockvalue
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getMockvalue() {
        return mockvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_t.mockvalue
     *
     * @param mockvalue the value for mock_t.mockvalue
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setMockvalue(String mockvalue) {
        this.mockvalue = mockvalue == null ? null : mockvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_t.mockdesc
     *
     * @return the value of mock_t.mockdesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getMockdesc() {
        return mockdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_t.mockdesc
     *
     * @param mockdesc the value for mock_t.mockdesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setMockdesc(String mockdesc) {
        this.mockdesc = mockdesc == null ? null : mockdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_t.m_exampleid
     *
     * @return the value of mock_t.m_exampleid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getmExampleid() {
        return mExampleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_t.m_exampleid
     *
     * @param mExampleid the value for mock_t.m_exampleid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setmExampleid(Integer mExampleid) {
        this.mExampleid = mExampleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_t.mock_frameid
     *
     * @return the value of mock_t.mock_frameid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getMockFrameid() {
        return mockFrameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_t.mock_frameid
     *
     * @param mockFrameid the value for mock_t.mock_frameid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setMockFrameid(Integer mockFrameid) {
        this.mockFrameid = mockFrameid;
    }
}