package com.importproject.enetity;

import java.io.Serializable;

public class Project implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_t.projectid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_t.projectdesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String projectdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_t.projectroot
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private String projectroot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_t
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_t.projectid
     *
     * @return the value of project_t.projectid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_t.projectid
     *
     * @param projectid the value for project_t.projectid
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_t.projectdesc
     *
     * @return the value of project_t.projectdesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getProjectdesc() {
        return projectdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_t.projectdesc
     *
     * @param projectdesc the value for project_t.projectdesc
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setProjectdesc(String projectdesc) {
        this.projectdesc = projectdesc == null ? null : projectdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_t.projectroot
     *
     * @return the value of project_t.projectroot
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public String getProjectroot() {
        return projectroot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_t.projectroot
     *
     * @param projectroot the value for project_t.projectroot
     *
     * @mbggenerated Sun Jan 17 10:34:23 CST 2021
     */
    public void setProjectroot(String projectroot) {
        this.projectroot = projectroot == null ? null : projectroot.trim();
    }
}